### ISSUE TITLE
Helpdesk 1.3.1 und Contao 2.11 

### ISSUE THREAD

**Issue by sabrik** [katgirl/contao-helpdesk#1]
Hi Kirsten!

Anbei der Code damit Helpdesk auch unter Contao 2.11 wieder richtig läuft.
https://www.contao-community.de/showthread.php?27669-Helpdesk-1-3-1-und-Contao-2-11

Mir ist noch aufgefallen das bei der aktuellen Version, die Dateien doppelt eingebunden sind.

**Comment by katgirl** [comment]
Ist bereits behoben. Allerdings ist die Lösung im Forum nicht zu empfehlen!

**Comment by katgirl** [comment]
dublicate #2
