### ISSUE TITLE
Function split() is deprecated

### ISSUE THREAD

**Issue by mvalex** [katgirl/contao-helpdesk#2]
Beim manuellen Aufruf der HelpdeskNotify.php durch einen externen ("echten") Cronjob erhalte ich eine Fehlermeldung:

Deprecated notice: Function split() is deprecated in /www/htdocs/user/WEB/system/modules/helpdesk/HelpdeskNotify.php on line 44
#0 [internal function]: __error(8192, 'Function split(...', '/www/htdocs/use...', 44, Array)

 #1 /www/htdocs/user/WEB/system/modules/helpdesk/HelpdeskNotify.php(44): split()
 #2 /www/htdocs/user/WEB/system/modules/helpdesk/HelpdeskNotify.php(63): HelpdeskNotify->hlog(1, 'Notification st...')
 #3 /www/htdocs/user/WEB/system/modules/helpdesk/HelpdeskNotify.php(605): HelpdeskNotify->run()
 #4 /www/htdocs/user/WEB/system/modules/helpdesk/HelpdeskNotifyExec.php(26): require_once('/www/htdocs/use...')
 #5 {main} 

Es müsste auf eine aktuelle PHP-Funktion umgestellt werden.

Gruß Alex

**Comment by katgirl** [comment]
siehe commit
