### ISSUE TITLE
Cron job Forum e-mail notification failed:

### ISSUE THREAD

**Issue by tobisnet** [katgirl/contao-helpdesk#3]
Im Systemlog tauchen die folgenden Fehlermeldungen auf, wenn die e-mail notification durch ist:
(contao 2.11.7 und helpdesk 1.3.10 Build 34)

Cron job Forum e-mail notification failed:
Warning: preg_split() [function.preg-split]: Empty regular expression in .../system/modules/helpdesk/HelpdeskNotify.php on line 44
#0 [internal function]: __error(2, 'preg_split() [<...', '/www/htdocs/...', 44, Array)
#1 .../system/modules/helpdesk/HelpdeskNotify.php(44): preg_split('?', 'Notification st...')
#2 .../system/modules/helpdesk/HelpdeskNotify.php(63): HelpdeskNotify->hlog(1, 'Notification st...')
#3 .../system/modules/helpdesk/HelpdeskNotify.php(605): HelpdeskNotify->run()
#4 .../system/modules/cron/CronController.php(143): include('/www/htdocs/...')
#5 .../system/modules/cron/CronController.php(89): CronController->runJob(Object(DB_Mysql_Result))
#6 .../system/modules/cron/CronController.php(248): CronController->run()
#7 .../system/modules/cron/CronIcon.php(28): include('/www/htdocs/...')
#8 {main}

Warning: Invalid argument supplied for foreach() in .../system/modules/helpdesk/HelpdeskNotify.php on line 45
#0 .../system/modules/helpdesk/HelpdeskNotify.php(45): __error(2, 'Invalid argumen...', '/www/htdocs/...', 45, Array)
#1 .../system/modules/helpdesk/HelpdeskNotify.php(63): HelpdeskNotify->hlog(1, 'Notification st...')
#2 .../system/modules/helpdesk/HelpdeskNotify.php(605): HelpdeskNotify->run()
#3 .../system/modules/cron/CronController.php(143): include('/www/htdocs/...')
#4 .../system/modules/cron/CronController.php(89): CronController->runJob(Object(DB_Mysql_Result))
#5 .../system/modules/cron/CronController.php(248): CronController->run()
#6 .../system/modules/cron/CronIcon.php(28): include('/www/htdocs/...')
#7 {main}

**Comment by llb4ll** [comment]
Contao 2.11.6 - Helpdesk 1.3.10 stable build 36
same error.

**Comment by katgirl** [comment]
@llb4ll hast du dir das mal angeschaut?

https://community.contao.org/de/showthread.php?3871-Hilfe-Seite-defekt-Fatal-Error&p=289104&viewfull=1#post289104

**Comment by llb4ll** [comment]
Danke für den Link - soeben ausprobiert, bekomme aber immer noch denselben Fehler wie oben :/

**Comment by katgirl** [comment]
see 773a7bf302a0d92338a40e1b2c91a824e9e80d49
